/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ass.pkg1_p04;

/**
 *
 * @author kevil-gandhi
 */
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class RetailCustomerApp extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RetailCustomerApp.class.getName());

    /**
     * Creates new form RetailCustomerApp
     */
    byte[] photoBytes;

    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    public RetailCustomerApp() {
        initComponents();

        try {
            con = DBConnection.getConnection();
            ps = con.prepareStatement("SELECT * FROM customers",
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs = ps.executeQuery();

            if (rs.next()) {
                fillFormFromResultSet(rs);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHomeAdd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHomePhNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBusinessAdd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBusinessPhNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPager = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        selectMaritalStatus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtNoOfChildren = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAnnualIncome = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnSelectPhoto = new javax.swing.JButton();
        btnAverageIncome = new javax.swing.JButton();
        btnAverageIncome1 = new javax.swing.JButton();
        btnAverageIncome2 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retail Customer Management");

        jLabel1.setText("Name");

        jLabel2.setText("Home Add.");

        jLabel3.setText("Home Phone No.");

        jLabel4.setText("Business Add.");

        jLabel5.setText("Business Phone No.");

        jLabel6.setText("Fax");

        jLabel7.setText("Mobile No.");

        lblPhoto.setText("Photo");
        lblPhoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("Pager");

        jLabel10.setText("Marital Status");

        selectMaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));

        jLabel11.setText("No. of Children");

        jLabel12.setText("Annual income");

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnFind.setText("Find");
        btnFind.addActionListener(this::btnFindActionPerformed);

        btnSelectPhoto.setText("Select Photo");
        btnSelectPhoto.addActionListener(this::btnSelectPhotoActionPerformed);

        btnAverageIncome.setText("Average Income");
        btnAverageIncome.addActionListener(this::btnAverageIncomeActionPerformed);

        btnAverageIncome1.setText("Next");
        btnAverageIncome1.addActionListener(this::btnAverageIncome1ActionPerformed);

        btnAverageIncome2.setText("Previous");
        btnAverageIncome2.addActionListener(this::btnAverageIncome2ActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusinessPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtHomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(55, 55, 55)
                                .addComponent(txtHomePhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel7)
                                .addGap(38, 38, 38)
                                .addComponent(txtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusinessAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30)
                                .addComponent(txtPager, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(btnAdd))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selectMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnUpdate)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnDelete))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(btnAverageIncome1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(btnAverageIncome2)
                                        .addGap(101, 101, 101)
                                        .addComponent(btnClear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(btnFind)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAverageIncome)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNoOfChildren, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(jLabel12)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAnnualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSelectPhoto))
                                        .addGap(31, 31, 31)))))
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtHomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtHomePhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtBusinessAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBusinessPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(txtPager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(selectMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtNoOfChildren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtAnnualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnFind)
                            .addComponent(btnAverageIncome))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAverageIncome1)
                            .addComponent(btnAverageIncome2)
                            .addComponent(btnClear)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSelectPhoto)))
                .addContainerGap(430, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPhotoActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select Photo");

        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File file = chooser.getSelectedFile();
                photoBytes = Files.readAllBytes(file.toPath());

                ImageIcon icon = new ImageIcon(photoBytes);
                Image img = icon.getImage().getScaledInstance(
                        lblPhoto.getWidth(),
                        lblPhoto.getHeight(),
                        Image.SCALE_SMOOTH
                );
                lblPhoto.setIcon(new ImageIcon(img));

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error loading photo");
            }
        }

    }//GEN-LAST:event_btnSelectPhotoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        try {
            ps = con.prepareStatement(
                    "INSERT INTO customers "
                    + "(name, home_address, home_phone, business_address, business_phone, "
                    + "fax, mobile, pager, marital_status, no_of_children, annual_income, photo) "
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)"
            );

            ps.setString(1, txtName.getText());
            ps.setString(2, txtHomeAdd.getText());
            ps.setString(3, txtHomePhNo.getText());
            ps.setString(4, txtBusinessAdd.getText());
            ps.setString(5, txtBusinessPhNo.getText());
            ps.setString(6, txtFax.getText());
            ps.setString(7, txtMobileNo.getText());
            ps.setString(8, txtPager.getText());
            ps.setString(9, selectMaritalStatus.getSelectedItem().toString());
            ps.setInt(10, Integer.parseInt(txtNoOfChildren.getText()));
            ps.setDouble(11, Double.parseDouble(txtAnnualIncome.getText()));
            ps.setBytes(12, photoBytes);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added Successfully");

            refreshResultSet();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed

        try {
            ps = con.prepareStatement(
                    "SELECT * FROM customers WHERE name = ?"
            );
            ps.setString(1, txtName.getText());

            rs = ps.executeQuery();

            if (rs.next()) {
                fillFormFromResultSet(rs);
                JOptionPane.showMessageDialog(this, "Record Found");
            } else {
                JOptionPane.showMessageDialog(this, "Record Not Found");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        refreshResultSet();

    }//GEN-LAST:event_btnFindActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        try {
            ps = con.prepareStatement(
                    "UPDATE customers SET "
                    + "home_address=?, home_phone=?, business_address=?, business_phone=?, "
                    + "fax=?, mobile=?, pager=?, marital_status=?, no_of_children=?, "
                    + "annual_income=?, photo=? "
                    + "WHERE name=?"
            );

            ps.setString(1, txtHomeAdd.getText());
            ps.setString(2, txtHomePhNo.getText());
            ps.setString(3, txtBusinessAdd.getText());
            ps.setString(4, txtBusinessPhNo.getText());
            ps.setString(5, txtFax.getText());
            ps.setString(6, txtMobileNo.getText());
            ps.setString(7, txtPager.getText());
            ps.setString(8, selectMaritalStatus.getSelectedItem().toString());
            ps.setInt(9, Integer.parseInt(txtNoOfChildren.getText()));
            ps.setDouble(10, Double.parseDouble(txtAnnualIncome.getText()));
            ps.setBytes(11, photoBytes);
            ps.setString(12, txtName.getText());

            int rows = ps.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Record Updated Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Update Failed (Record not found)");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this record?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            ps = con.prepareStatement(
                    "DELETE FROM customers WHERE name = ?"
            );
            ps.setString(1, txtName.getText());

            int rows = ps.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Record Deleted");
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Record Not Found");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        refreshResultSet();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAverageIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAverageIncomeActionPerformed

        try {
            // Call stored procedure
            CallableStatement cs
                    = con.prepareCall("{CALL getAvgIncomeOfMarried(?)}");

            // Register OUT parameter
            cs.registerOutParameter(1, Types.DOUBLE);

            // Execute procedure
            cs.execute();

            // Get result
            double avgIncome = cs.getDouble(1);

            // Handle NULL (no married customers)
            if (cs.wasNull()) {
                JOptionPane.showMessageDialog(
                        this,
                        "No married customers found",
                        "Average Income",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Average Annual Income of Married Customers:\n₹ " + avgIncome,
                        "Average Income",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }

            cs.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error calling procedure:\n" + ex.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAverageIncomeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAverageIncome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAverageIncome1ActionPerformed

        try {
            if (rs != null && rs.next()) {
                fillFormFromResultSet(rs);
            } else {
                JOptionPane.showMessageDialog(this, "This is the last record");
                if (rs != null) {
                    rs.previous(); // stay on last valid record
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnAverageIncome1ActionPerformed

    private void btnAverageIncome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAverageIncome2ActionPerformed

        try {
            if (rs != null && rs.previous()) {
                fillFormFromResultSet(rs);
            } else {
                JOptionPane.showMessageDialog(this, "This is the first record");
                if (rs != null) {
                    rs.next(); // stay on first valid record
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnAverageIncome2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RetailCustomerApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAverageIncome;
    private javax.swing.JButton btnAverageIncome1;
    private javax.swing.JButton btnAverageIncome2;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnSelectPhoto;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JComboBox<String> selectMaritalStatus;
    private javax.swing.JTextField txtAnnualIncome;
    private javax.swing.JTextField txtBusinessAdd;
    private javax.swing.JTextField txtBusinessPhNo;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHomeAdd;
    private javax.swing.JTextField txtHomePhNo;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoOfChildren;
    private javax.swing.JTextField txtPager;
    // End of variables declaration//GEN-END:variables

    private void fillFormFromResultSet(ResultSet rs) throws Exception {

        txtName.setText(rs.getString("name"));
        txtHomeAdd.setText(rs.getString("home_address"));
        txtHomePhNo.setText(rs.getString("home_phone"));
        txtBusinessAdd.setText(rs.getString("business_address"));
        txtBusinessPhNo.setText(rs.getString("business_phone"));
        txtFax.setText(rs.getString("fax"));
        txtMobileNo.setText(rs.getString("mobile"));
        txtPager.setText(rs.getString("pager"));
        selectMaritalStatus.setSelectedItem(rs.getString("marital_status"));
        txtNoOfChildren.setText(rs.getString("no_of_children"));
        txtAnnualIncome.setText(rs.getString("annual_income"));

        byte[] img = rs.getBytes("photo");
        if (img != null) {
            ImageIcon icon = new ImageIcon(img);
            Image scaled = icon.getImage().getScaledInstance(
                    lblPhoto.getWidth(),
                    lblPhoto.getHeight(),
                    Image.SCALE_SMOOTH
            );
            lblPhoto.setIcon(new ImageIcon(scaled));
            photoBytes = img;
        }
    }

    private void clearForm() {
        txtName.setText("");
        txtHomeAdd.setText("");
        txtHomePhNo.setText("");
        txtBusinessAdd.setText("");
        txtBusinessPhNo.setText("");
        txtFax.setText("");
        txtMobileNo.setText("");
        txtPager.setText("");
        txtNoOfChildren.setText("");
        txtAnnualIncome.setText("");
        lblPhoto.setIcon(null);
        photoBytes = null;
    }

    private void refreshResultSet() {

        try {
            ps = con.prepareStatement(
                    "SELECT * FROM customers",
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY
            );
            rs = ps.executeQuery();

            if (rs.next()) {
                fillFormFromResultSet(rs);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

}
